---
- name: Deploy FastAPI server to AWS EC2 with nginx
  hosts: modelapiserver
  become: true
  tasks:
    - name: Update package repository
      apt:
        update_cache: yes

    - name: Clone the github repo
      git:
        repo: https://github.com/12-Twelvve/modelapi.git
        dest: /home/ubuntu/modelapi
        clone: yes

    - name: Install venv and nginx
      apt:
        name: 
          - python3.10-venv
          - nginx
        state: present

    - name: Create Python virtual environment
      command: python3 -m venv venv
    - name: Add execute permission to activate script
      shell: chmod +x /home/ubuntu/venv/bin/activate

    - name: Activate Python virtual environment
      shell: /home/ubuntu/venv/bin/activate

    
    - name: Install Python dependencies using pip
      pip:
        requirements: /home/ubuntu/modelapi/requirements.txt
        executable: /home/ubuntu/venv/bin/pip

    - name: Copy censor.service file
      copy:
        src: /home/ubuntu/modelapi/censor.service
        dest: /etc/systemd/system/censor.service
        owner: root
        group: root
        mode: 0644
        remote_src: yes

    - name: Reload systemd to pick up changes
      systemd:
        daemon_reload: yes
      become: yes

    - name: Start the censor service
      systemd:
        name: censor
        state: started
        enabled: yes
      become: yes

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: true

    - name: Copy Nginx configuration file
      copy:
        src: /home/ubuntu/modelapi/default
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: 0644
        remote_src: yes

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Check status of censor service
      become: true
      systemd:
        name: censor
        state: status
      register: censor_status

    - name: Notify if censor service failed
      debug:
        msg: "censor service is {{ censor_status.status }}. Please check."
      when: censor_status.status == "failed"