---
- name: Deploy Flask App on AWS EC2
  hosts: censorappserver
  become: true

  tasks:
    - name: Update package repository
      apt:
        update_cache: yes

    - name: Clone the Webapp repository
      git:
        repo: https://github.com/12-Twelvve/censorapp.git
        dest: /home/ubuntu/censorapp
        clone: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy index.html file to /var/www/html
      copy:
        src: /home/ubuntu/censorapp/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
        remote_src: yes

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
    